#!/usr/bin/env python
import cgitb
import json
import cgi
import psycopg2
import sys
import db

cgitb.enable()    

print("Content-Type: text/html;charset=utf-8\n\n")
conn = psycopg2.connect(db.conn_string)
cursor = conn.cursor()
data = sys.stdin.read()
f = open("/tmp/register.txt","w")
f.write(data)
f.close()
d = json.loads(data)
uinf = d["user_info"]
user = uinf["name"]
device = uinf["deviceid"]

query = "insert into user_devices(user_id,device_id) values ('%s','%s')"%(user,device)

cursor.execute(query)
conn.commit()
conn.close()

